extends Node

const WORLD_BITMASK = 1 << 0
const PLAYER_BITMASK = 1 << 1
const LIGHT_BITMASK = 1 << 2
const LIGHT_BLOCKER_BITMASK = 1 << 3
const LIGHT_REFLECTOR_BITMASK = 1 << 4
const HOLDABLE_BITMASK = 1 << 5
const PLAYER_HOLDABLE_CHECK_BITMASK = 1 << 6
const VOID_BITMASK = 1 << 7

const WORLD_LAYER = 1
const PLAYER_LAYER = 2
const LIGHT_LAYER = 3
const LIGHT_BLOCKER_LAYER = 4
const LIGHT_REFLECTOR_LAYER = 5
const HOLDABLE_LAYER = 6
const PLAYER_HOLDABLE_CHECK_LAYER = 7
const VOID_LAYER = 8